// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSerial(arg1) {
  return window['go']['main']['App']['ConnectSerial'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAvailablePorts() {
  return window['go']['main']['App']['GetAvailablePorts']();
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetKey'](arg1, arg2, arg3);
}

export function StartListen() {
  return window['go']['main']['App']['StartListen']();
}

export function StopListen() {
  return window['go']['main']['App']['StopListen']();
}

export function UsePresetKeys(arg1) {
  return window['go']['main']['App']['UsePresetKeys'](arg1);
}
