// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSerial(arg1:string):Promise<string>;

export function Disconnect():void;

export function GetAvailablePorts():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function StartListen():void;

export function StopListen():void;
