// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ConnectSerial(arg1:string):Promise<string>;

export function Disconnect():void;

export function GetAvailablePorts():Promise<Array<app.SerialOptions>>;

export function GetDevices():Promise<Array<app.SerialOptions>>;

export function Greet(arg1:string):Promise<string>;

export function SetKey(arg1:string,arg2:number,arg3:string):void;

export function StartListen():void;

export function StopListen():void;

export function UsePresetKeys(arg1:string):void;
